### ISSUE TITLE
在战斗（对撞）过程中点画面左边的技能可以跳过动画节省时间，可以请作者加进去吗

### ISSUE THREAD

**Issue by ZhuYi98** [zhoubin-me/lushi_script#106]
在战斗（对撞）过程中点画面左边的技能可以跳过动画节省时间，可以请作者加进去吗，谢谢！

**Comment by blacksilvergeek** [comment]
加这个太容易出bug了，因为这个状态不好找特征识别的东西，很容易导致奇怪的时候点击引起的bug

**Comment by littlewrite** [comment]
我试了下，感觉没加速多少。
真要加速，那还得上齿轮。
