### ISSUE TITLE
运行出错winguiautoError：No top level window found for wantedText='炉石传说'

### ISSUE THREAD

**Issue by ckk777** [zhoubin-me/lushi_script#110]
![QQ图片20211104004430](https://user-images.githubusercontent.com/47133795/140104771-08a343a8-8121-46b4-805e-740700cb531a.png)

**Comment by zhoubin-me** [comment]
开炉石了么

**Comment by ckk777** [comment]
> 开炉石了么

感谢，解决了！开炉石后可以运行。
