### ISSUE TITLE
版本更新后经常卡死

### ISSUE THREAD

**Issue by Biu-Bong** [zhoubin-me/lushi_script#117]
[新版本更新了英雄，时不时的会往外弹窗口，然后脚本就卡住了。见下图

而在重启之后，有时候会卡住宝箱，这个截图忘记截了
![1636066279(1)](https://user-images.githubusercontent.com/35222512/140431463-964cb330-bd63-4325-bb42-8683647d3566.png)

**Comment by xim9160** [comment]
重启卡住宝箱+1 
另外最近应该是网易/暴雪服务器抽风, 掉线率非常高, 我人盯着差不多 1 小时掉2 次线

**Comment by blacksilvergeek** [comment]
宝箱问题解决，版本更新进游戏弹出新页面不好解决，因为页面是不确定的
