### ISSUE TITLE
奖励选不到

### ISSUE THREAD

**Issue by ap430** [zhoubin-me/lushi_script#121]
英文1024*768
红框奖励选不中
![{{W8S7HDW$B5R0OC4(V8D76](https://user-images.githubusercontent.com/93373887/140514477-75d6efe4-b50f-4907-9b9a-5afc1c1e651a.png)

**Comment by zhoubin-me** [comment]
奖励数设对了么

**Comment by ap430** [comment]
是的 发现是奖励数错了 感谢
