### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Yafasd** [zhoubin-me/lushi_script#122]
在对战一开始后程序直接闪退
![image](https://user-images.githubusercontent.com/86545585/140525903-c8ba7073-e8ee-4bf0-86ea-1f37979c27e3.png)

**Comment by ioxv** [comment]
尝试使用shell运行python main_gui.py，如果运行的release的with_python版本，请尝试运行debug.bat。如果有闪退情况，提交一下shell中的报错信息看看...

**Comment by Yafasd** [comment]
![image](https://user-images.githubusercontent.com/86545585/140592695-76fa3b6d-96f2-4478-b57f-22fa48431ece.png)

**Comment by ioxv** [comment]
检查一下配置是否正确，比如炉石路径是否填写正确，修改完成记得保存...

**Comment by Yafasd** [comment]
已经解决 炉石路径未配置正确导致
