### ISSUE TITLE
指定神秘人奖励选择偶尔失效、出现3宝藏技能都被排除时会卡住。

### ISSUE THREAD

**Issue by L0ra** [zhoubin-me/lushi_script#124]
2个情况。
1.在heros_whitelist文件夹放入了红龙的图片，打出神秘人后，3选1出现红龙，有时不选红龙，选其他2个。偶尔出现。
2.在treasure_blacklist文件夹放入一些想排除的技能，当出现3个技能奖励都在排除选项中时，有时会等待较长时间后随机选一个，有时会卡在选择界面，一动不动。

**Comment by Huangyan0804** [comment]
已修复
