### ISSUE TITLE
窗口分辨率的建议

### ISSUE THREAD

**Issue by war4den** [zhoubin-me/lushi_script#131]
用现在的xy坐标分别除以1600 和900 得到一个比率 在yaml里存这个比率 英文中文就能用一个了
然后用比率乘以现在窗口的宽 高 
就可以随意窗口大小了

**Comment by someash** [comment]
感觉难点好像并不是缩放比率，而是获取炉石窗口的大小，不知道能不能参考Hearthstone Deck Tracker的方法，它能在准确的地方显示对方技能，应该可以参考参考

**Comment by Huangyan0804** [comment]
有些ui并不是按比例缩放的

**Comment by eatmoreforall** [comment]
我有一个可行的方案。
可以通过修改  例如：（C:\Users\admin\AppData\Local\Blizzard\Hearthstone）下 options.txt 中
graphicsheight=900
graphicswidth=1600
实现窗口确定
手动可行，希望在程序里实现自动加载。

**Comment by blacksilvergeek** [comment]
> 我有一个可行的方案。 可以通过修改 例如：（C:\Users\admin\AppData\Local\Blizzard\Hearthstone）下 options.txt 中 graphicsheight=900 graphicswidth=1600 实现窗口确定 手动可行，希望在程序里实现自动加载。

这和直接改分辨率效果不一样吗？

**Comment by eatmoreforall** [comment]
> > 我有一个可行的方案。 可以通过修改 例如：（C:\Users\admin\AppData\Local\Blizzard\Hearthstone）下 options.txt 中 graphicsheight=900 graphicswidth=1600 实现窗口确定 手动可行，希望在程序里实现自动加载。
> 
> 这和直接改分辨率效果不一样吗？

有些分辨率在游戏里面没法设置
