### ISSUE TITLE
建议增加点击查询并导入队伍内英雄功能

### ISSUE THREAD

**Issue by someash** [zhoubin-me/lushi_script#132]
就在我的队伍，然后在具体队伍界面，点击读取队伍 后自动识别那六个名字，然后加入配置的队伍里

**Comment by blacksilvergeek** [comment]
main下现在已经实现了

> 就在我的队伍，然后在具体队伍界面，点击读取队伍 后自动识别那六个名字，然后加入配置的队伍里

**Comment by someash** [comment]
6666
