### ISSUE TITLE
宝藏黑名单问题

### ISSUE THREAD

**Issue by whynotbanm** [zhoubin-me/lushi_script#137]
当宝藏出现的三个均在黑名单上时，脚本会卡住
建议宝藏使用白名单

**Comment by someash** [comment]
我建议宝藏和神秘人任务都采用可以切换黑/白名单的形式，这样就方便各种需求的了。。。

**Comment by whynotbanm** [comment]
> 我建议宝藏和神秘人任务都采用可以切换黑/白名单的形式，这样就方便各种需求的了。。。

我感觉这种切换式的。。。。代码实现难度比只设成白名单要大一些（激将法！）

**Comment by someash** [comment]
黑白名单的所需要的截图是不是得到神秘人选择/宝藏选择上去截图，在酒馆里截图有用吗？

**Comment by littlewrite** [comment]
> 当宝藏出现的三个均在黑名单上时，脚本会卡住 建议宝藏使用白名单

现在优化这个了，三个都在，会从中随机选一个。
再一个目前版本我们推荐的黑名单机制，把所有主动技能的速度图片放到黑名单中，这样就不会选主动技能（拿了脚本也不会放）。这样拿到buff技能的机会加大，身材大了就无脑过关了。
