### ISSUE TITLE
Discord error

### ISSUE THREAD

**Issue by Nox1k** [zhoubin-me/lushi_script#144]
Hello could someone give correct link to discord please?

**Comment by Huangyan0804** [comment]
我们已经没有discord群组了

**Comment by Nox1k** [comment]
Thank you

**Comment by Nox1k** [comment]
Does script work with Russian language? I have a error shows that could find window on the top. HS is opened.

**Comment by Huangyan0804** [comment]
当前并不支持俄语，可以调整语言为英语，分辨率为1024x768使用

**Comment by Nox1k** [comment]
Thank you!
