### ISSUE TITLE
Choosing 2-n or heroic bosses

### ISSUE THREAD

**Issue by Nox1k** [zhoubin-me/lushi_script#151]
Could someone please show how to choose 2-5,2-6 bosses or heroic mode?

**Comment by Huangyan0804** [comment]
First select the boss number, then manually enter the level you want to go to, and then it will be selected automatically.

**Comment by Huangyan0804** [comment]
If you have any questions, please join discord group in README.

**Comment by Nox1k** [comment]
Thank you, I’ve asked this question in discord too. How can I choose heroic? 2-1 means heroic or normal?

**Comment by Huangyan0804** [comment]
First select the  level you want to go manually, then retire the map, and then start the script, it will select the last level automatically.

**Comment by Nox1k** [comment]
Thank you
