### ISSUE TITLE
关卡奖励卡住

### ISSUE THREAD

**Issue by facination08** [zhoubin-me/lushi_script#157]
如题，选奖励时卡住，版本0.4.2
[2021-12-02.log](https://github.com/zhoubin-me/lushi_script/files/7642411/2021-12-02.log)

![restart_21 39 28,991](https://user-images.githubusercontent.com/94054760/144434339-d5349199-65ae-49fa-933e-f70581ac50ff.png)

**Comment by Mercit1** [comment]
自己截个图 命名为final reward和reward2就好了

**Comment by Cholover** [comment]
> 

求问截图了放在哪个文件夹里啊，要改哪个code吗

**Comment by Mercit1** [comment]
> 求问截图了放在哪个文件夹里啊，要改哪个code吗
![Uploading DFF95891-9F12-44D6-B828-1B34658BC297.png…]()

**Comment by Mercit1** [comment]
> 求问截图了放在哪个文件夹里啊，要改哪个code吗

final_reward.png和final_reward2.png替换到\resource\imgs_chs_1600x900\icons\下

**Comment by Cholover** [comment]
> > 求问截图了放在哪个文件夹里啊，要改哪个code吗
> 
> final_reward.png和final_reward2.png替换到\resource\imgs_chs_1600x900\icons\下

谢谢谢谢~
