### ISSUE TITLE
script works fine right until the combat starts. what to do?

### ISSUE THREAD

**Issue by cachai** [zhoubin-me/lushi_script#170]
I installed python 3.7 and visual basic and did alll the things and got the latest script and all that.
It even starts the game for me and goes into the fight.
And then it doesn't try to do the combat and stay clicking on the bottom right doing nothing. 
I don't know why exactly tho so any help would be appreciated. 
thanks for the program btw it has been great saving my time and sanity.
(It has been working on my laptop, but not on my desktop, same 1920x1080 resolution monitor and 1600x900 simplified chinese versions)

**Comment by Nox1k** [comment]
I think script doesn’t work after new patch. We need to modify script

**Comment by cachai** [comment]
> I think script doesn’t work after new patch. We need to modify script

Maybe not well with the new characters, but I am having no problems with my usual automatic party on my laptop right now(Ragnaros Geddon Antonidas + Garrosh Saurfang  Edwin). Same comp/same stage does not work on my desktop for some reason. It's sad because I want to let desktop earn my coins while I am out with my notebook.

**Comment by Nox1k** [comment]
After previous update blizzard changed some icons (for example treasure, some buttons) so script may stucks. May be the same issue with new update.

**Comment by blacksilvergeek** [comment]
> I think script doesn’t work after new patch. We need to modify script

Dependency packages need to be updated after new patch. Run pip install like the FAQ shown, this might help.

**Comment by blacksilvergeek** [comment]
> I installed python 3.7 and visual basic and did alll the things and got the latest script and all that. It even starts the game for me and goes into the fight. And then it doesn't try to do the combat and stay clicking on the bottom right doing nothing. I don't know why exactly tho so any help would be appreciated. thanks for the program btw it has been great saving my time and sanity. (It has been working on my laptop, but not on my desktop, same 1920x1080 resolution monitor and 1600x900 simplified chinese versions)

Maybe check the hearthstone path or you can check the log files to find information about the bug
