### ISSUE TITLE
反馈进不了旅行的问题

### ISSUE THREAD

**Issue by 9527ddd** [zhoubin-me/lushi_script#202]
我看文件里的 travel 图片是旧版佣兵战纪的截图，因此从主界面进入佣兵战纪后不会再自动进关卡，换成新版截图就行了

**Comment by 370455671** [comment]
你好 我自己截图替换taravel.png 好像不行 请问是有什么分辨率要求或者别的要求吗？

**Comment by 9527ddd** [comment]
> 你好 我自己截图替换taravel.png 好像不行 请问是有什么分辨率要求或者别的要求吗？

用qq截图就行，还有你是不是把travel拼错了
