### ISSUE TITLE
当神秘选项在中间的时候经常会选到旁边的选项，有头绪吗

### ISSUE THREAD

**Issue by ill-never-retreat** [zhoubin-me/lushi_script#5]

**Comment by ill-never-retreat** [comment]
感谢回复。还有一个问题，我试图通过识别boss旁边的宝箱，来直接结束当前轮次，但只是偶尔识别成功，这种情况是为什么呢

**Comment by zhoubin-me** [comment]
你可以push到自己的fork我看看么

**Comment by ill-never-retreat** [comment]
已经上传了，第一次稍微有点慢。
目前的情况是，神秘人除非看起来在左实际在右的情况都可以精确找到（我把两种情况的旋涡都判断了一下）
在找宝箱的时候，会在点完确认后才去摸一下地下中间的按钮

**Comment by ill-never-retreat** [comment]
之前只是在git上看看别人的代码，自己是第一次上传，我是不是设置成private了
