### ISSUE TITLE
skill_priority设定部分无用

### ISSUE THREAD

**Issue by someash** [zhoubin-me/lushi_script#64]
1.config_chs.yaml的43行注释有问题
2.设定的技能顺序1: [2, 1, 0]时，一直尝试第三技能，尝试次数达到skill_selection设定值时脚本直接退出，并没有因为在cd尝试第二技能和第一技能

**Comment by zhoubin-me** [comment]
不是无用。。是识别不出来CD标志。。后来发现是坐标偏移了。。就很诡异

**Comment by someash** [comment]
> 不是无用。。是识别不出来CD标志。。后来发现是坐标偏移了。。就很诡异。。。本机上没问题，虚拟机上出问题

那我等睡醒了再试试吧，我昨天用的时候是在本地win11上跑的，好像不行

**Comment by someash** [comment]
经过测试，功能可正常使用，不过config_chs.yaml的43行注释还是有问题
原：       # 比如 0: [2, 0, 1]意味着第一个英雄优先放第三个技能，如在CD中则放第一个技能，第一个也在CD中则放第三个技能
应该改成# 比如 0: [2, 0, 1]意味着第一个英雄优先放第三个技能，如在CD中则放第一个技能，第一个也在CD中则放第**二**个技能
