### ISSUE TITLE
0.2.6.1English Version 颜色识别有误

### ISSUE THREAD

**Issue by DarkBramble** [zhoubin-me/lushi_script#65]
util.py  analyse_battle_field模块，有时会将英雄颜色识别为'n'，导致误判而自动投降

**Comment by zhoubin-me** [comment]
我在本机上测试没问题，但是在虚拟机上一试就有问题。。。debug发现虚拟机里坐标偏移了。。。

**Comment by RommyYao** [comment]
@zhoubin-me 可以把find_coordinates程序改成一个初始化程序，让用户先走一遍流程，并把鼠标移到相应的位置，从而更新像投降、角色位置这些必要的坐标。
