### ISSUE TITLE
技能释放状态识别有误

### ISSUE THREAD

**Issue by xim9160** [zhoubin-me/lushi_script#70]
多次发生 其中一个佣兵技能点了释放, 然后另外两个没点上 010
然后重新点变成 101, 这样卡循环了

**Comment by blacksilvergeek** [comment]
把delay改高一点就好了，感觉原先的delay不适用了

**Comment by zhoubin-me** [comment]
v0.3.0 新版本不再给予cv了，试试看

**Comment by xim9160** [comment]
> v0.3.0 新版本不再给予cv了，试试看

试了下 0.3.0 版本, 稳定性高很多, delay 调 1.0 之后, 昨天一晚上能正常刷
