### ISSUE TITLE
config的bug

### ISSUE THREAD

**Issue by blacksilvergeek** [zhoubin-me/lushi_script#77]
![image](https://user-images.githubusercontent.com/46051884/139531206-cda5ff79-977b-492e-8368-f606854ff538.png)
疑似前两个元素间不能自动添加|\\
导致无法正确导入log文件，手动添加\\能正常运行

**Comment by someash** [comment]
你把E改成D，把项Games删掉就行了，应该是更新后还没检查一致性🙃

**Comment by blacksilvergeek** [comment]
> 你把E改成D，把项Games删掉就行了，应该是更新后还没检查一致性🙃

真有bug，我说的不是你说的问题，是要加\\的问题

**Comment by zaw007** [comment]
路径拼接是有问题的，os.path.join 在windows下必须在盘符后面加 \\，否则生成的路径是 C:Game 而不是期望的 C:\\Game
