### ISSUE TITLE
对面给自己招衍生物会报KeyError: 'LETL_823H3_05'

### ISSUE THREAD

**Issue by outloo** [zhoubin-me/lushi_script#78]
测试环境：非发行版，main（21/10/30 18h）版本
测试设备：版本	Windows 10 pro 20H2
前置条件：对面给自己招衍生物
测试结果：
![QQ截图20211030200445](https://user-images.githubusercontent.com/22869710/139532219-fc7ff363-d539-413f-97b3-ec0977ff8c0c.png)

![QQ图片20211030200643](https://user-images.githubusercontent.com/22869710/139532250-97f3ffb2-6c63-41d8-8e80-84fe50a95f3b.png)
复现率:100%

**Comment by Huangyan0804** [comment]
明天再修复

**Comment by zhoubin-me** [comment]
已修复
