### ISSUE TITLE
ModuleNotFoundError: No module named 'hearthstone'

### ISSUE THREAD

**Issue by ColinZYL** [zhoubin-me/lushi_script#82]
C:\Users\Administrator\Desktop\lushi_script-0.3.0>python lushi.py --lang chs
Traceback (most recent call last):
  File "lushi.py", line 12, in <module>
    from log_util.log_util import LogUtil
  File "C:\Users\Administrator\Desktop\lushi_script-0.3.0\log_util\log_util.py", line 1, in <module>
    from hearthstone.enums import CardType, Zone, GameTag
ModuleNotFoundError: No module named 'hearthstone'

**Comment by ColinZYL** [comment]
炉石安装路径的问题

**Comment by ColinZYL** [comment]
已经搞定

**Comment by NoOne-9527** [comment]
请问是怎么解决这个问题的？我也没找到需要填炉石安装路径的啊？

**Comment by NoOne-9527** [comment]
> 已经搞定

请问是怎么解决这个问题的？我也没找到需要填炉石安装路径的啊？

**Comment by cncndl** [comment]
@NoOne-9527 你有没有执行 `install.bat` 或者 `python -m pip install -r requirements.txt` ？
