### ISSUE TITLE
没有炉石模块- -

### ISSUE THREAD

**Issue by Chenwq297** [zhoubin-me/lushi_script#83]
![123](https://user-images.githubusercontent.com/93448911/139555489-61705ff9-6064-4dad-919e-f81af7eeaca9.png)
e'

**Comment by NoOne-9527** [comment]
> ![123](https://user-images.githubusercontent.com/93448911/139555489-61705ff9-6064-4dad-919e-f81af7eeaca9.png) e'
请问是怎么解决这个问题的？

**Comment by Chenwq297** [comment]
运行脚本文件夹内的install.bat下载模块即可




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月7日(星期天) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [zhoubin-me/lushi_script] 没有炉石模块- - (Issue #83)






伊
请问是怎么解决这个问题的？

—
您正在接收此消息，因为您修改了打开/关闭状态。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.
