### ISSUE TITLE
扫描地图进入战斗后会不断重启或者卡死

### ISSUE THREAD

**Issue by adf123** [zhoubin-me/lushi_script#95]
已参照FAQ设置战网与log地址，并使用官方助手生成log，但是扫描地图进入战斗后会不断重启或者卡死在下英雄阶段，没有其他提示，仅
Last state , time taken: 0.5136547088623047, side: None, surprise_in_mid: False
然后就不断
Battle.net.exe killed
attempt to start Battle.net
重复了

**Comment by Huangyan0804** [comment]
请确认日志路径设置正确，详情看FAQ最后一条

**Comment by adf123** [comment]
是参照FAQ设置的路径，
参照
hs_log: [ "D:\\", "Hearthstone", "Logs", "Power.log" ]
我的
# 战网路径(注意路径要加双斜杠)
  bn_path: ["D:\\", "游戏","炉石", "Battle.net", "Battle.net.exe"] # 'D:\\游戏\\炉石\\Battle.net\\Battle.net.exe'
  # 炉石日志路径
  hs_log: ["D:\\", "游戏", "炉石","Hearthstone", "GPUCache", "Hearthstone", "Logs", "Power.log"] # 'D:\\游戏\\炉石\\Hearthstone\\GPUCache\\Hearthstone\\Logs\\Power.log'

**Comment by adf123** [comment]
> 请确认日志路径设置正确，详情看FAQ最后一条

是参照FAQ设置的路径，
参照
hs_log: [ "D:\", "Hearthstone", "Logs", "Power.log" ]
我的
bn_path: ["D:\", "游戏","炉石", "Battle.net", "Battle.net.exe"] # 'D:\游戏\炉石\Battle.net\Battle.net.exe'
hs_log: ["D:\", "游戏", "炉石","Hearthstone", "GPUCache", "Hearthstone", "Logs", "Power.log"] # 'D:\游戏\炉石\Hearthstone\GPUCache\Hearthstone\Logs\Power.log'

**Comment by Huangyan0804** [comment]
双斜杠
