### ISSUE TITLE
Why keep saying  "No module named 'hslog'"?

### ISSUE THREAD

**Issue by IrvingZou** [zhoubin-me/lushi_script#99]
The path for 'power.log' is correct.

**Comment by xim9160** [comment]
pip install -r requirements.txt

**Comment by IrvingZou** [comment]
![image](https://user-images.githubusercontent.com/90711160/139664516-0aa99b4f-3199-42d9-ad26-c2d2aebaf4f0.png)

**Comment by IrvingZou** [comment]
> pip install -r requirements.txt

Thanks for your reply, but still got an Error as above.

**Comment by IrvingZou** [comment]
Is it because I am using Python 3.10, not Python 3.6?

**Comment by someash** [comment]
no，you need microsoft visual c++

**Comment by IrvingZou** [comment]
![image](https://user-images.githubusercontent.com/90711160/139792908-262da3b3-3790-4480-8401-e2881723841c.png)
Got 14.29 already, but still have this situation.

**Comment by Huangyan0804** [comment]
We recommend using python 3.7 or python 3.8
